"""Per-agent memory export — human-readable markdown, independent of QMD.

:class:`~core.qmd_generator.QMDGenerator` only exports ``Memory`` rows with
``shared=True`` (the Obsidian "Knowledge" tree is meant to be curated/shared
content). Every existing row defaults ``shared=False``, so pre-existing
memories never show up there — that's by design for the shared knowledge
base, but it means there was no human-readable export of an agent's *own*
memories at all. This module is that: one file per active memory, grouped by
``agent_id``, regardless of the ``shared`` flag.

Output layout (relative to ``HCC_AGENT_EXPORT_DIR``, default
``~/workspace/AICore/agents``)::

    agents/README.md                 <- index of all agent_id subdirectories
    agents/<agent_id>/README.md      <- per-agent index
    agents/<agent_id>/<slug>.md      <- one memory per file, YAML frontmatter
"""

from __future__ import annotations

import logging
import os
import re
import tempfile
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

import yaml
from sqlalchemy import select
from sqlalchemy.ext.asyncio import async_sessionmaker

from core.config import CoreSettings, core_settings
from gateway.core.database import async_session
from gateway.models import Memory, MemoryStatus

logger = logging.getLogger(__name__)


def _slugify(text: str, *, max_len: int = 60) -> str:
    text = (text or "").strip().lower()
    slug = re.sub(r"[^\w]+", "-", text, flags=re.UNICODE).strip("-")
    slug = re.sub(r"-{2,}", "-", slug)
    if len(slug) > max_len:
        slug = slug[:max_len].rstrip("-")
    return slug or "untitled"


@dataclass
class AgentExportStats:
    total_memories: int = 0
    agents: dict[str, int] = field(default_factory=dict)
    files_written: int = 0

    def as_dict(self) -> dict:
        return {
            "total_memories": self.total_memories,
            "agents": self.agents,
            "files_written": self.files_written,
        }


class AgentExporter:
    """Export every active memory as markdown, grouped by ``agent_id``."""

    def __init__(
        self,
        *,
        settings: CoreSettings | None = None,
        session_factory: async_sessionmaker | None = None,
    ) -> None:
        self._settings = settings or core_settings
        self._session_factory = session_factory or async_session

    @property
    def root(self) -> Path:
        return Path(self._settings.agent_export_dir).expanduser()

    @staticmethod
    def _title(memory: Memory) -> str:
        summary = (memory.summary or "").strip()
        if summary:
            return summary.splitlines()[0][:100]
        content = (memory.content or "").strip()
        if content:
            return content.splitlines()[0][:100]
        return f"Memory {memory.id[:8]}"

    @staticmethod
    def _fmt_dt(value: datetime | None) -> str:
        if value is None:
            return ""
        return value.isoformat()

    def _render_memory(self, memory: Memory) -> str:
        frontmatter = {
            "id": memory.id,
            "type": memory.type,
            "agent_id": memory.agent_id,
            "user_id": memory.user_id,
            "importance": memory.importance,
            "tags": list(memory.tags or []),
            "shared": bool(memory.shared),
            "timestamp": self._fmt_dt(memory.updated_at or memory.created_at),
            "created_at": self._fmt_dt(memory.created_at),
        }
        fm_yaml = yaml.safe_dump(frontmatter, sort_keys=False, allow_unicode=True).strip()
        title = self._title(memory)
        parts = [f"---\n{fm_yaml}\n---", f"# {title}", ""]
        if memory.summary and memory.summary.strip() != title:
            parts.append(f"> {memory.summary.strip()}\n")
        parts.append((memory.content or "").strip())
        return "\n".join(parts).rstrip() + "\n"

    def _render_agent_index(self, agent_id: str, entries: list[tuple[str, Memory]]) -> str:
        lines = [
            f"# {agent_id}",
            "",
            f"_{len(entries)} memory(ies). Auto-generated by HCC AgentExporter — 请勿手编。_",
            "",
        ]
        for slug, memory in sorted(entries, key=lambda e: e[0]):
            title = self._title(memory)
            lines.append(f"- [{title}]({slug}.md)")
        lines.append("")
        return "\n".join(lines)

    def _render_master_index(self, grouped: dict[str, list[tuple[str, Memory]]]) -> str:
        total = sum(len(v) for v in grouped.values())
        stamp = datetime.now(timezone.utc).isoformat()
        lines = [
            "# Agent Memory Exports",
            "",
            "> 本目录由 HCC AgentExporter 自动生成，请勿手编。按 agent_id 分目录，"
            "导出全部 active 记忆（不受 QMDGenerator 的 shared=True 过滤限制）。",
            "",
            f"_Auto-generated on {stamp}._",
            "",
            f"Total memories: **{total}**",
            "",
            "## Agents",
            "",
        ]
        for agent_id in sorted(grouped):
            lines.append(f"- [{agent_id}]({agent_id}/README.md) ({len(grouped[agent_id])})")
        lines.append("")
        return "\n".join(lines)

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(dir=str(path.parent), suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as fh:
                fh.write(content)
                fh.flush()
                os.fsync(fh.fileno())
            os.replace(tmp_name, path)
        except BaseException:
            try:
                os.unlink(tmp_name)
            except OSError:
                pass
            raise

    async def _fetch_memories(self) -> list[Memory]:
        async with self._session_factory() as session:
            result = await session.execute(
                select(Memory).where(Memory.status == MemoryStatus.ACTIVE).order_by(Memory.agent_id, Memory.created_at)
            )
            return list(result.scalars().all())

    async def generate_all(self) -> AgentExportStats:
        memories = await self._fetch_memories()
        stats = AgentExportStats(total_memories=len(memories))

        grouped: dict[str, list[tuple[str, Memory]]] = {}
        seen_slugs: dict[str, set[str]] = {}
        for memory in memories:
            agent_id = memory.agent_id or "default"
            base_slug = _slugify(self._title(memory))
            used = seen_slugs.setdefault(agent_id, set())
            slug = base_slug
            n = 1
            while slug in used:
                n += 1
                slug = f"{base_slug}-{n}"
            used.add(slug)
            grouped.setdefault(agent_id, []).append((slug, memory))

        written_paths: set[Path] = set()
        for agent_id, entries in grouped.items():
            for slug, memory in entries:
                path = self.root / agent_id / f"{slug}.md"
                self._atomic_write(path, self._render_memory(memory))
                written_paths.add(path)
                stats.files_written += 1
            stats.agents[agent_id] = len(entries)

            index_path = self.root / agent_id / "README.md"
            self._atomic_write(index_path, self._render_agent_index(agent_id, entries))

        self._atomic_write(self.root / "README.md", self._render_master_index(grouped))

        # Prune files for memories that no longer exist/are inactive (mirrors
        # QMDGenerator's orphan handling, but agent exports aren't part of the
        # shared knowledge base so stale files are just removed, not archived).
        if self.root.exists():
            for existing in self.root.rglob("*.md"):
                if existing.is_file() and existing.name.lower() != "readme.md" and existing not in written_paths:
                    try:
                        existing.unlink()
                    except OSError:
                        logger.warning("failed to remove stale agent export file %s", existing)

        logger.info("agent export complete: %s", stats.as_dict())
        return stats


async def _amain() -> None:
    exporter = AgentExporter()
    stats = await exporter.generate_all()
    print("Agent export complete:")
    for key, value in stats.as_dict().items():
        print(f"  {key}: {value}")


def main() -> None:
    import asyncio

    logging.basicConfig(level=logging.INFO, format="%(levelname)s %(name)s: %(message)s")
    asyncio.run(_amain())


if __name__ == "__main__":
    main()
