"""Workspace Optimizer — manages Agent workspace lifecycle.

The Optimizer is the key difference between HCC and a simple memory system.
It:
1. Scans Agent workspace for markdown files
2. Imports any unabsorbed content via Scanner
3. Removes files that have been absorbed into PostgreSQL
4. Rewrites bootstrap files (MEMORY.md, SOUL.md, USER.md) as HCC guides
5. Keeps workspace lean — only bootstrap files + unprocessed daily notes
"""

from __future__ import annotations

import logging
import os
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Files that are ALWAYS kept (bootstrap/guide files)
BOOTSTRAP_FILES = {"AGENTS.md", "SOUL.md", "USER.md", "TOOLS.md", "MEMORY.md", "CLAUDE.md"}

# Files that can be deleted after absorption
ABSORBABLE_PATTERNS = [
    r"memory/\d{4}-\d{2}-\d{2}\.md",   # daily notes: memory/2026-07-15.md
    r"DREAMS?\.md",                      # dream output
    r"dreams?/.*\.md",                   # dream directory
    r"notes?/.*\.md",                    # general notes
    r"snapshots?/.*\.md",               # snapshots
    r"session.*\.md",                    # session exports
    r"\d{4}-\d{2}-\d{2}\.md",           # root daily notes
]

# HCC-style bootstrap content
BOOTSTRAP_TEMPLATES: dict[str, str] = {
    "MEMORY.md": """# Memory Management

This workspace is managed by **Hanyan Cognitive Core (HCC)**.

## Policy

- **HCC is the single source of truth** for all long-term memory.
- Do NOT duplicate long-term memories in this file.
- This file is regenerated by HCC after each session.

## How to use memory

1. **Search** — When you need to recall something, use `search_memory()`
2. **Store** — Only store durable facts through HCC via `store_memory()`
3. **Session cache** — Temporary notes go into `memory/YYYY-MM-DD.md`; HCC will absorb and delete them

## Current state

*Last optimized: {timestamp}*
*Memories in HCC: {memory_count}*
*Active preferences: {preferences}*

---

*This file is auto-generated by HCC. Edits will be preserved across regenerations.*
""",
    "SOUL.md": """# Identity & Personality

Your identity and personality are maintained by **Hanyan Cognitive Core (HCC)**.

## Guidelines

- Personality is NOT stored in this file. It lives in HCC's Personality Engine.
- HCC tracks preferences, emotional baselines, and trait evolution.
- If your personality feels inconsistent, query HCC via `get_personality()`.

## Current personality profile

*Last synced: {timestamp}*
*Active traits: {traits}*

## How to use

When asked about identity, preferences, or emotional state:
1. Query `HCC Personality Engine` via `get_personality()`
2. Query `HCC Emotion Engine` via `get_emotion()`
3. Store meaningful interactions via `store_memory()`

---

*This file is auto-generated by HCC. Your core identity directives below this line are preserved.*
""",
    "USER.md": """# User Profile

User information is maintained by **Hanyan Cognitive Core (HCC)**.

## Policy

- Do NOT store user profile data in this file.
- HCC tracks user preferences, relationships, and history.
- Query HCC for user information when needed.

## How to use

1. Query `search_memory(user_id="michael")` for user context
2. Use `get_personality()` for preference information
3. Store new user information via `store_memory()`

---

*This file is auto-generated by HCC.*
""",
}


class WorkspaceOptimizer:
    """Manages Agent workspace: absorb, compress, rewrite, delete.

    Typical workflow per session:
    1. Pre-session: generate bootstrap files from HCC data
    2. During session: Scanner absorbs Agent's writes in real time
    3. Post-session: Optimizer scans, deletes absorbed files, rewrites bootstraps
    """

    def __init__(self, workspace_dir: str | Path | None = None):
        self._workspace_dir = Path(workspace_dir) if workspace_dir else None

    @property
    def workspace(self) -> Path | None:
        return self._workspace_dir

    @workspace.setter
    def workspace(self, path: str | Path) -> None:
        self._workspace_dir = Path(path)

    # ── Scan ────────────────────────────────────────────────────────────────

    def scan_for_absorbable(self) -> list[Path]:
        """Find files that can be absorbed and then deleted."""
        if not self._workspace_dir or not self._workspace_dir.exists():
            return []

        absorbable: list[Path] = []
        for f in self._workspace_dir.rglob("*.md"):
            rel = f.relative_to(self._workspace_dir)
            rel_str = str(rel.as_posix())

            # Skip bootstrap files
            if rel.name in BOOTSTRAP_FILES:
                continue

            # Check if matches absorbable patterns
            for pattern in ABSORBABLE_PATTERNS:
                if re.match(pattern, rel_str):
                    absorbable.append(f)
                    break

        return sorted(absorbable)

    def scan_all_files(self) -> dict[str, list[Path]]:
        """Categorize all markdown files in workspace."""
        if not self._workspace_dir or not self._workspace_dir.exists():
            return {"bootstrap": [], "absorbable": [], "other": []}

        result: dict[str, list[Path]] = {"bootstrap": [], "absorbable": [], "other": []}
        absorbable_set = set(self.scan_for_absorbable())

        for f in self._workspace_dir.rglob("*.md"):
            if f.name in BOOTSTRAP_FILES:
                result["bootstrap"].append(f)
            elif f in absorbable_set:
                result["absorbable"].append(f)
            else:
                result["other"].append(f)

        return result

    # ── Absorbed file management ────────────────────────────────────────────

    def mark_as_absorbed(self, file_path: Path) -> bool:
        """Move an absorbed file to a .hcc-absorbed backup or delete it.

        Returns True if the file was removed.
        """
        if not file_path.exists():
            return False

        # Option 1: Delete directly (clean)
        file_path.unlink()
        logger.info("optimizer: deleted absorbed file %s", file_path)
        return True

    def delete_absorbed_files(self, dry_run: bool = False) -> list[Path]:
        """Delete all absorbable files. Returns list of deleted paths."""
        to_delete = self.scan_for_absorbable()
        if dry_run:
            logger.info("optimizer: dry-run, would delete %d files", len(to_delete))
            return to_delete

        deleted = []
        for f in to_delete:
            try:
                self.mark_as_absorbed(f)
                deleted.append(f)
            except OSError as e:
                logger.warning("optimizer: failed to delete %s: %s", f, e)

        # Clean up empty directories
        self._cleanup_empty_dirs()

        logger.info("optimizer: deleted %d/%d absorbable files", len(deleted), len(to_delete))
        return deleted

    def _cleanup_empty_dirs(self) -> None:
        """Remove empty directories left after file deletion."""
        if not self._workspace_dir:
            return
        for dirpath, dirnames, filenames in self._workspace_dir.walk():
            if not dirnames and not filenames and dirpath != self._workspace_dir:
                try:
                    dirpath.rmdir()
                except OSError:
                    pass

    # ── Bootstrap file generation ───────────────────────────────────────────

    def generate_bootstrap(self, memory_count: int = 0,
                           preferences: list[str] | None = None,
                           traits: list[str] | None = None) -> dict[str, str]:
        """Generate bootstrap file contents with HCC metadata."""
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        prefs = ", ".join(preferences[:5]) if preferences else "none tracked"
        trait_str = ", ".join(traits[:5]) if traits else "learning..."

        return {
            name: template.format(
                timestamp=now,
                memory_count=memory_count,
                preferences=prefs,
                traits=trait_str,
            )
            for name, template in BOOTSTRAP_TEMPLATES.items()
        }

    def write_bootstrap(self, contents: dict[str, str] | None = None,
                        memory_count: int = 0,
                        preferences: list[str] | None = None,
                        traits: list[str] | None = None) -> list[Path]:
        """Write bootstrap files to workspace. Returns written paths."""
        if not self._workspace_dir:
            logger.warning("optimizer: no workspace dir set")
            return []

        self._workspace_dir.mkdir(parents=True, exist_ok=True)
        if contents is None:
            contents = self.generate_bootstrap(memory_count, preferences, traits)

        written = []
        for name, content in contents.items():
            path = self._workspace_dir / name
            # Preserve user edits below HCC auto-generated section
            if path.exists():
                existing = path.read_text(encoding="utf-8", errors="replace")
                # Only replace if the file looks HCC-generated
                if "auto-generated by HCC" not in existing:
                    logger.info("optimizer: preserving manual %s (not HCC-generated)", name)
                    continue

            path.write_text(content, encoding="utf-8")
            written.append(path)
            logger.info("optimizer: wrote bootstrap %s", path)

        return written

    # ── Full optimization cycle ─────────────────────────────────────────────

    def optimize(self, dry_run: bool = False,
                 memory_count: int = 0,
                 preferences: list[str] | None = None,
                 traits: list[str] | None = None) -> dict[str, Any]:
        """Run the full optimization cycle.

        1. Scan for absorbable files
        2. Delete absorbed files
        3. Regenerate bootstrap files
        """
        if not self._workspace_dir:
            return {"status": "no_workspace", "deleted": 0, "written": 0}

        logger.info("optimizer: starting optimization of %s", self._workspace_dir)

        # Step 1: Scan
        scan = self.scan_all_files()
        logger.info("optimizer: found %d bootstrap, %d absorbable, %d other",
                     len(scan["bootstrap"]), len(scan["absorbable"]), len(scan["other"]))

        # Step 2: Delete absorbed files
        deleted = self.delete_absorbed_files(dry_run=dry_run) if not dry_run else scan["absorbable"]

        # Step 3: Generate and write bootstrap files
        contents = self.generate_bootstrap(memory_count, preferences, traits)
        written = self.write_bootstrap(contents, memory_count, preferences, traits)

        result = {
            "status": "dry_run" if dry_run else "optimized",
            "workspace": str(self._workspace_dir),
            "bootstrap_files": len(scan["bootstrap"]),
            "absorbable_found": len(scan["absorbable"]),
            "absorbable_deleted": len(deleted),
            "other_files": len(scan["other"]),
            "bootstrap_written": len(written),
        }
        logger.info("optimizer: optimization complete: %s", result)
        return result


# Singleton
_optimizer: WorkspaceOptimizer | None = None


def get_optimizer(workspace_dir: str | Path | None = None) -> WorkspaceOptimizer:
    global _optimizer
    if _optimizer is None:
        _optimizer = WorkspaceOptimizer(workspace_dir)
    elif workspace_dir and _optimizer.workspace is None:
        _optimizer.workspace = workspace_dir
    return _optimizer
