"""Workspace Optimizer — manages Agent workspace lifecycle."""

from __future__ import annotations

import logging
import os
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

BOOTSTRAP_FILES = {"AGENTS.md", "SOUL.md", "USER.md", "TOOLS.md", "MEMORY.md", "CLAUDE.md",
                   "IDENTITY.md", "HEARTBEAT.md", "ARCHITECTURE.md", "CROSS_AGENT_COMMS.md",
                   "README.md", "INVENTORY.md", "OPENCLAW_SKILLS.md"}

ABSORBABLE_PATTERNS = [
    r"DREAMS?\.md",
    r"dream/.*\.md",
    r"memory/.*\.md",
    r"memory/.*",
    r"memory$",
    r"notes?/.*\.md",
    r"snapshots?/.*\.md",
]


class WorkspaceOptimizer:
    def __init__(self, workspace_dir: str | Path | None = None):
        self._workspace_dir = Path(workspace_dir) if workspace_dir else None

    @property
    def workspace(self) -> Path | None:
        return self._workspace_dir

    @workspace.setter
    def workspace(self, path: str | Path) -> None:
        self._workspace_dir = Path(path)

    def scan_for_absorbable(self) -> list[Path]:
        if not self._workspace_dir or not self._workspace_dir.exists():
            return []
        absorbable: list[Path] = []
        for f in self._workspace_dir.rglob("*"):
            if not f.is_file() or f.suffix != ".md":
                continue
            rel = f.relative_to(self._workspace_dir)
            rel_str = rel.as_posix()
            if rel.name in BOOTSTRAP_FILES:
                continue
            for pattern in ABSORBABLE_PATTERNS:
                if re.match(pattern, rel_str):
                    absorbable.append(f)
                    break
        return sorted(absorbable)

    def scan_all_files(self) -> dict[str, list[Path]]:
        if not self._workspace_dir or not self._workspace_dir.exists():
            return {"bootstrap": [], "absorbable": [], "other": []}
        result = {"bootstrap": [], "absorbable": [], "other": []}
        s = set(self.scan_for_absorbable())
        for f in self._workspace_dir.rglob("*.md"):
            if f.name in BOOTSTRAP_FILES:
                result["bootstrap"].append(f)
            elif f in s:
                result["absorbable"].append(f)
            else:
                result["other"].append(f)
        return result

    def delete_absorbed_files(self, dry_run: bool = False) -> list[Path]:
        to_delete = self.scan_for_absorbable()
        if dry_run:
            return to_delete
        deleted = []
        for f in to_delete:
            try:
                f.unlink()
                deleted.append(f)
            except OSError as e:
                logger.warning("optimizer: failed to delete %s: %s", f, e)
        return deleted

    def generate_bootstrap(self, memory_count: int = 0,
                           preferences: list[str] | None = None,
                           traits: list[str] | None = None) -> dict[str, str]:
        now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        prefs = ", ".join(preferences[:5]) if preferences else "none tracked"
        trait_str = ", ".join(traits[:5]) if traits else "learning..."
        return {
            "MEMORY.md": f"""# Memory Management

This workspace is managed by **Hanyan Cognitive Core (HCC)**.

## Policy

- **HCC is the single source of truth** for all long-term memory.
- Do NOT duplicate long-term memories in this file.
- This file is regenerated by HCC after each session.

## How to use memory

1. **Search** — When you need to recall something, use HCC `search_memory()`
2. **Store** — Only store durable facts through HCC via `store_memory()`
3. **Session cache** — Temporary notes go into `memory/YYYY-MM-DD.md`; HCC will absorb them

## Current state

*Last optimized: {now}*
*Memories in HCC: {memory_count}*
*Active preferences: {prefs}*

---

*This file is auto-generated by HCC.*
""",
            "SOUL.md": f"""# Identity & Personality

Your identity and personality are maintained by **Hanyan Cognitive Core (HCC)**.

## Guidelines

- Personality is NOT stored in this file. It lives in HCC's Personality Engine.
- HCC tracks preferences, emotional baselines, and trait evolution.
- If your personality feels inconsistent, query HCC via `get_personality()`.

## Current state

*Last synced: {now}*
*Active traits: {trait_str}*

---

*This file is auto-generated by HCC.*
""",
            "USER.md": f"""# User Profile

User information is maintained by **Hanyan Cognitive Core (HCC)**.

## Policy

- Do NOT store user profile data in this file.
- HCC tracks user preferences, relationships, and history.
- Query HCC for user information when needed.

---

*This file is auto-generated by HCC.*
""",
        }

    def write_bootstrap(self, contents: dict[str, str]) -> list[Path]:
        if not self._workspace_dir:
            return []
        self._workspace_dir.mkdir(parents=True, exist_ok=True)
        written = []
        for name, content in contents.items():
            path = self._workspace_dir / name
            path.write_text(content, encoding="utf-8")
            written.append(path)
        return written
